apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-service
  labels:
    app: simple-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-service
  template:
    metadata:
      labels:
        app: simple-service
    spec:
      containers:
        - name: simple-service
          image: simple-service
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-node
  labels:
    app: worker-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-node
  template:
    metadata:
      labels:
        app: worker-node
    spec:
      containers:
        - name: simple-service
          image: simple-service
          imagePullPolicy: Never
          command: ["python"]
          args: ["-u", "worker.py"]
          env:
            - name: SCHEDULER_SERVICE_CONNECT
              value: simple-service:80
---
apiVersion: v1
kind: Service
metadata:
  name: simple-service
spec:
  selector:
    app: simple-service
  ports:
    - port: 80
  type: LoadBalancer
