apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-worker
  labels:
    app: add-worker
    app-role: calc-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: add-worker
  template:
    metadata:
      labels:
        app: add-worker
    spec:
      containers:
        - name: add-worker
          image: arczipt/http-worker
          #imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
          - name: OP
            value: ADD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-kafka-worker
  labels:
    app: add-kafka-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: add-kafka-worker
  template:
    metadata:
      labels:
        app: add-kafka-worker
    spec:
      containers:
        - name: add-kafka-worker
          image: arczipt/kafka-worker
          #imagePullPolicy: Never
          env:
          - name: OP
            value: ADD
